__title__ = 'rapic'
__description__ = 'Automatically generate api client libraries/sdk for websites, online services and 3rd party private api.'
__url__ = 'https://github.com/ydaniels/rapic'
__version__ = '0.1.5'
__author__ = 'Yomi D'
__author_email__ = 'yomid4all@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2020 Yomi D'